export const NEW_BUSINESS_NOTIFICATION = 'NEW_BUSINESS_NOTIFICATION'
export const NEW_PROFILE_NOTIFICATION = 'NEW_PROFILE_NOTIFICATION'
export const NEW_NETWORK_NOTIFICATION = 'NEW_NETWORK_NOTIFICATION'